fos_user:
    db_driver: orm
    firewall_name: main
    user_class: JbNahan\PsBundle\Entity\User

    registration:
        confirmation:
            enabled: true
    from_email:
        address:        noreply@status.com
        sender_name:    Status App