services:
#    jb_nahan_ps.example:
#        class: JbNahan\PsBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]