JbNahan\PsBundle\Entity\Photo:
    type: entity
    table: ps_photo
    repositoryClass: JbNahan\PsBundle\Repository\PhotoRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        uploadedAt:
            type: datetime
        deletedAt:
            type: datetime
            nullable: true
        viewcount:
            type: integer
            nullable: true
    manyToOne:
        album:
            targetEntity: Album
            inversedBy: photos
            joinColumns:
                album:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
